version: '3.7'

services:
  fluentd:
    image: fluentd:v1.16.2
    container_name: fluentd
    hostname: fluentd
    user: root
    ports:
      - 24224:24224
    volumes:
      - ./fluent.conf:/fluentd/etc/fluent.conf
      - /data/logs:/data/logs
      - /etc/localtime:/etc/localtime
    networks:
        - proxynet

networks:
  proxynet:
    name: elasticsearch_elk